---
- name: Install nginx
  sudo: yes
  apt:  pkg=nginx state=latest

- name: Configure nginx vhost
  sudo: yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: Restart nginx

